trigger:
  - master
pr:
  - master
jobs:
  - template: ci/azure-install-deps.yml
  - job: run_tests
    displayName: Run Tests
    strategy:
      matrix:
        Linux:
          vmImage: ubuntu-16.04
        MacOS:
          vmImage: macOS-10.13
        Windows:
          vmImage: vs2017-win2016
    pool:
      vmImage: $(vmImage)
    steps:
        - script: |
            cargo fmt --all -- --check
            cargo test
          displayName: cargo test -p toshi
          workingDirectory: $(Build.SourcesDirectory)/toshi
          condition: succeeded()
  - template: ci/azure-run-kcov.yml