trigger:
  - master

pr:
  - master

jobs:
  - template: ci/azure-install-apt-deps.yml
    condition: eq( variables['Agent.OS'], 'Linux' )

  - template: ci/azure-rustfmt.yml
    parameters: rustfmt

  - job: ${{ parameters.name }}
    displayName: ${{ parameters.displayName }}
    strategy:
      matrix:
        Linux:
          vmImage: ubuntu-16.04
        MacOS:
          vmImage: macOS-10.13
        Windows:
          vmImage: vs2017-win2016
    pool:
      vmImage: $(vmImage)

    steps:
        - script: cargo test
          displayName: cargo test -p ${{ crate }}
          workingDirectory: $(Build.SourcesDirectory)/${{ crate }}
          condition: and(succeeded(), not(variables['isRelease']))

  - template: ci/azure-install-kcov.yml
    condition: eq( variables['Agent.OS'], 'Linux' )