trigger:
  - master
pr:
  - master
jobs:
  - job: run_tests
    displayName: Run Tests
    strategy:
      matrix:
        Linux-Stable:
          imageName: ubuntu-16.04
          rustup_toolchain: stable
        MacOS-Stable:
          imageName: macOS-10.13
          rustup_toolchain: stable
        Windows-Stable:
          imageName: vs2017-win2016
          rustup_toolchain: stable
        Linux-Nightly:
          imageName: ubuntu-16.04
          rustup_toolchain: nightly
          optional: true
        MacOS-Nightly:
          imageName: macOS-10.13
          rustup_toolchain: nightly
          optional: true
        Windows-Nightly:
          imageName: vs2017-win2016
          rustup_toolchain: nightly
          optional: true
    pool:
      vmImage: $(imageName)
    steps:
        - template: ci/azure-install-deps.yml
        - script: |
            cargo fmt --all -- --check
            cargo test
          displayName: cargo test
        - template: ci/azure-run-kcov.yml
        - script: |
            echo "##vso[task.complete result=Succeeded;]DONE"
          condition: eq(${{parameters.optional}}, true)