trigger:
  - master

pr:
  - master

jobs:
  - template: ci/azure-install-deps.yml

  - template: ci/azure-rustfmt.yml

  - job: Run Tests
    displayName: Run Tests
    strategy:
      matrix:
        Linux:
          vmImage: ubuntu-16.04
        MacOS:
          vmImage: macOS-10.13
        Windows:
          vmImage: vs2017-win2016
    pool:
      vmImage: $(vmImage)

    steps:
        - script: cargo test
          displayName: cargo test -p toshi
          workingDirectory: $(Build.SourcesDirectory)/toshi
          condition: and(succeeded())

  - template: ci/azure-run-kcov.yml