trigger:
  - master
pr:
  - master
jobs:
  - job: run_tests
    displayName: Run Tests
    strategy:
      matrix:
        Linux-Stable:
          imageName: ubuntu-16.04
          rust_toolchain: stable
        MacOS-Stable:
          imageName: macOS-10.13
          rust_toolchain: stable
        Windows-Stable:
          imageName: vs2017-win2016
          rust_toolchain: stable
        Linux-Nightly:
          imageName: ubuntu-16.04
          rust_toolchain: nightly
        MacOS-Nightly:
          imageName: macOS-10.13
          rust_toolchain: nightly
        Windows-Nightly:
          imageName: vs2017-win2016
          rust_toolchain: nightly
    pool:
      vmImage: $(imageName)
    steps:
        - template: ci/azure-install-deps.yml
        - script: |
            cargo fmt --all -- --check
            cargo test
          displayName: cargo test
        - template: ci/azure-run-kcov.yml