[bans]
multiple-versions = "deny"
deny = [
    # color-backtrace is nice but brings in too many dependencies and that are often outdated, so not worth it for us.
    { name = "color-backtrace" },

    # dirs crate has a lot of dependencies and there are better alternatives
    { name = "dirs" },
    { name = "dirs-sys" },

    # deprecated
    { name = "quickersort" },

    # term is not fully maintained, and termcolor is replacing it
    { name = "term" },
]
skip = [
    { name = "crossbeam-queue", version = "=0.2.0" },
    { name = "bytes", version = "=0.4.12" },
]
skip-tree = [
    { name = "rand", version = "=0.6.5" },
    { name = "syn",  version = "=0.15.44" },
]