jobs:
  # Check formatting
  - job: Install rustfmt
    displayName: Check rustfmt
    pool:
      vmImage: $(vmImage)
    steps:
      - script: |
          cargo fmt --all -- --check
        displayName: Check formatting