[package]
name    = "toshi-types"
version = "0.1.1"
authors = ["Stephen Carman <shcarman@gmail.com>"]
description = "A types for full text search engine based on Tantivy"
repository = "https://github.com/toshi-search/Toshi"
license = "MIT"
edition = "2018"

[dependencies]
http = "^0.1"
failure = "^0.1"
serde = "^1.0"
serde_json = "^1.0"
tantivy = "^0.10"
hyper = "^0.12"